# Generated by Django 5.2.4 on 2025-07-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=100)),
                ('min_cart_value', models.IntegerField()),
                ('max_cart_value', models.IntegerField()),
                ('discount_percent', models.IntegerField()),
                ('coupon_stat', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_coupon',
            },
        ),
    ]
