# Generated by Django 5.2.4 on 2025-08-14 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0005_ordermodel_first_name_ordermodel_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderlogModel',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_dateandtime', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(db_column='order_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='logs_by_order', to='Orders.ordermodel')),
                ('status', models.ForeignKey(db_column='status', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='logs_by_status', to='Orders.ordermodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_orderlogs',
            },
        ),
    ]
