# Generated by Django 5.2.4 on 2025-08-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlogmodel',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
