# Generated by Django 5.2.4 on 2025-08-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminOrders', '0002_alter_orderlogmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlogmodel',
            name='user_id',
        ),
    ]
