# Generated by Django 5.2.4 on 2025-07-22 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminCategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryModel',
            fields=[
                ('subcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcat_name', models.CharField(max_length=100)),
                ('subcat_image', models.CharField(max_length=100)),
                ('cat_id', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='AdminCategories.categorymodel')),
            ],
            options={
                'db_table': 'tbl_subcategory',
            },
        ),
    ]
