# Generated by Django 5.2.4 on 2025-07-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminCategories', '0001_initial'),
        ('AdminSubcategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymodel',
            name='cat_id',
            field=models.ForeignKey(db_column='cat_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminCategories.categorymodel'),
        ),
    ]
