# Generated by Django 5.2.4 on 2025-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
    ]
