# Generated by Django 5.2.4 on 2025-08-01 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminProducts', '0004_alter_productmodel_product_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(db_column='product_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminProducts.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
    ]
