# Generated by Django 5.2.4 on 2025-07-27 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminSubcategory', '0002_alter_subcategorymodel_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=200)),
                ('product_specification', models.CharField(max_length=200)),
                ('retail_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('thumbnail_image', models.CharField(max_length=100)),
                ('image1', models.CharField(max_length=100)),
                ('image2', models.CharField(max_length=100)),
                ('image3', models.CharField(max_length=100)),
                ('Video_url', models.CharField(max_length=100)),
                ('is_active', models.CharField(max_length=100)),
                ('subcat_id', models.ForeignKey(db_column='cat_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminSubcategory.subcategorymodel')),
            ],
        ),
    ]
