# Generated by Django 5.2.4 on 2025-07-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodel',
            table='tbl_products',
        ),
    ]
