# Generated by Django 5.2.4 on 2025-07-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProducts', '0002_alter_productmodel_table'),
        ('AdminSubcategory', '0002_alter_subcategorymodel_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='subcat_id',
            field=models.ForeignKey(db_column='subcat_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminSubcategory.subcategorymodel'),
        ),
    ]
