# Generated by Django 5.2.4 on 2025-07-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProducts', '0003_alter_productmodel_subcat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_specification',
            field=models.TextField(),
        ),
    ]
