# Generated by Django 5.2.4 on 2025-08-04 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_payment', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('addressline1', models.CharField(max_length=100)),
                ('addressline2', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('orderdatetime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
    ]
