# Generated by Django 5.2.4 on 2025-08-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='contactnumber',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
