# Generated by Django 5.2.4 on 2025-08-05 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProducts', '0004_alter_productmodel_product_description_and_more'),
        ('Orders', '0002_ordermodel_contactnumber_alter_ordermodel_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item_price', models.IntegerField()),
                ('product_id', models.ForeignKey(db_column='product_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminProducts.productmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_items',
            },
        ),
    ]
