# Generated by Django 5.2.4 on 2025-08-05 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_id',
        ),
        migrations.AddField(
            model_name='item',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Orders.ordermodel'),
        ),
    ]
