# Generated by Django 5.2.4 on 2025-08-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminProducts', '0004_alter_productmodel_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(db_column='product_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminProducts.productmodel')),
            ],
            options={
                'db_table': 'tbl_reviews',
            },
        ),
    ]
